### ISSUE TITLE
Initial build error

### ISSUE THREAD

**Issue by j-joshua** [alexeilebedev/openacr#1]
Initial build after clone:

```
$ ai
# this script has been created using make bootstrap
# now building an abt executable which will build the rest
++ mkdir -p temp
++ mkdir -p dflt.release-x86_64
++ echo dev.gitinfo
++ ld -r -b binary gitinfo.txt -o dflt.release-x86_64/gitinfo.o
++ rm -f gitinfo.txt
++ g++ -O2 -Werror -ffunction-sections -fdata-sections -Wsequence-point -Wno-multichar -Wall -Wshadow -pipe -Wextra -Winit-self -Wmissing-include-dirs -Wmissing-declarations -Winvalid-pch -DUNAME_LINUX -iquote . -msse4.2 -D AOS_SSE42 -Wno-vla -Wno-unused-local-typedefs -Wno-long-long -Wno-strict-aliasing -fpch-preprocess -Wpedantic -c include/algo_pch.h -o dflt.release-x86_64/include.algo_pch.h.gch
In file included from ./include/algo.h:59,
                 from include/algo_pch.h:26:
./include/algo.inl.h: In function ‘void algo::qCall(const algo::THook<>&)’:
./include/algo.inl.h:573:18: error: cast between incompatible function types from ‘algo::THook<>::HookFcn’ {aka ‘void (*)(void*, algo::NotUsed*, algo::NotUsed*, algo::NotUsed*)’} to ‘Func’ {aka ‘void (*)(void*)’} [-Werror=cast-function-type]
     Func(hook.fcn)(hook.ctx);
                  ^
cc1plus: all warnings being treated as errors

```

**Comment by j-joshua** [comment]
$ g++ --version
g++ (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)

**Comment by alexeilebedev** [comment]
I will need to spawn an instance with gcc 8.3 and see what's wrong
Thanks

-------- Original Message --------

**Comment by alexeilebedev** [comment]
I was able to progress by adding a few options to both bin/abt-bootstrap and data/dev/tool_opt.ssim:

```
+dev.tool_opt  tool_opt:488  opt_type:CC_OPTS  opt:-Wno-error=cast-function-type  target:""  uname:""  compiler:g++  cfg:""  arch:""  comment:""
+dev.tool_opt  tool_opt:489  opt_type:CC_OPTS  opt:-Wno-error=class-memaccess  target:""  uname:""  compiler:g++  cfg:""  arch:""  comment:""
```

For backtrace.cpp, we should use ucontext_t:

```
diff --git a/cpp/lib/algo/backtrace.cpp b/cpp/lib/algo/backtrace.cpp
index b48109a..0a80f7d 100644
--- a/cpp/lib/algo/backtrace.cpp
+++ b/cpp/lib/algo/backtrace.cpp
@@ -63,0 +64 @@
+#include <ucontext.h>
@@ -239 +240 @@ static void Signal(int signal, siginfo_t *_si, void *context) {
-    uintptr_t ip = context ? (uintptr_t)(((struct ucontext *)context)->uc_mcontext.gregs[REG_RIP]) : 0;
+    uintptr_t ip = context ? (uintptr_t)(((ucontext_t *)context)->uc_mcontext.gregs[REG_RIP]) : 0;
diff --git a/cpp/lib/algo/fmt.cpp b/cpp/lib/algo/fmt.cpp
index 7cf47ca..46fd56e 100644
--- a/cpp/lib/algo/fmt.cpp
+++ b/cpp/lib/algo/fmt.cpp
@@ -452 +452 @@ bool algo::Ipmask_ReadStrptrMaybe(Ipmask &row, algo::strptr str) {
-                bits = -1 << (32-bits);
+                bits = u32(-1) << (32-bits);

```

But sadly, I get a segfault when running abt, and I'm not able to debug it yet, because mdbg can't be built. I will bring in binaries from CentOS to see what's happening, but I think it has to do with algo_lib's hook implementation (via template savagery) being no longer valid with gcc ABI version 13. I may need to fully move hooks into amc.

I tried using 

```
+dev.tool_opt  tool_opt:490  opt_type:CC_OPTS  opt:-fabi-version=11  target:""  uname:""  compiler:g++  cfg:""  arch:""  comment:""
```

But haven't had success yet. It still segfaults.

**Comment by alexeilebedev** [comment]
Should now work with gcc 8 and Ubuntu

**Comment by j-joshua** [comment]
`# this script has been created using make bootstrap                                                                                                                      
# now building an abt executable which will build the rest                                                                                                               
++ mkdir -p temp                                                                                                                                                         
++ mkdir -p dflt.release-x86_64                                                                                                                                          
++ echo dev.gitinfo                                                                                                                                                      
++ ld -r -b binary gitinfo.txt -o dflt.release-x86_64/gitinfo.o                                                                                                          
++ rm -f gitinfo.txt                                                                                                                                                     
++ g++ -O -Werror -ffunction-sections -fdata-sections -Wsequence-point -Wno-multichar -Wall -Wshadow -pipe -Wextra -Winit-self -Wmissing-include-dirs -Wmissing-declarat$
ons -Winvalid-pch -DUNAME_LINUX -iquote . -msse4.2 -D AOS_SSE42 -Wno-vla -Wno-unused-local-typedefs -Wno-long-long -Wno-strict-aliasing -fpch-preprocess -Wno-cast-funct$
on-type -Wno-class-memaccess -Wpedantic -c include/algo_pch.h -o dflt.release-x86_64/include.algo_pch.h.gch                                                              
In file included from ./include/algo.h:34,                                                                                                                               
                 from include/algo_pch.h:26:                                                                                                                             ./include/gen/algo_gen.h: In copy constructor ‘algo::LnumStr10_U64::LnumStr10_U64(const algo::LnumStr10_U64&)’:                                                          
./include/gen/algo_gen.h:2244:23: error: implicitly-declared ‘constexpr algo::LnumStr10_U64& algo::LnumStr10_U64::operator=(const algo::LnumStr10_U64&)’ is deprecated [$
Werror=deprecated-copy]                                                                                                                                                  
 2244 |         operator =(rhs);                                                                                                                                         
      |                       ^                                                                                                                                          
./include/gen/algo_gen.h:2243:5: note: because ‘algo::LnumStr10_U64’ has user-provided ‘algo::LnumStr10_U64::LnumStr10_U64(const algo::LnumStr10_U64&)’                  
 2243 |     LnumStr10_U64(const algo::LnumStr10_U64 &rhs) {                                                                                                              
      |     ^~~~~~~~~~~~~                                                                                                                                                
`

**Comment by alexeilebedev** [comment]
Can you paste compiler & OS version?

**Comment by j-joshua** [comment]
```
 jjoshua  ~  uname -a
Linux bigtop.jjoshua.com 5.0.11-300.fc30.x86_64 #1 SMP Thu May 2 14:11:38 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 jjoshua  ~  g++ --version
g++ (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1)

```

I just upgraded to Fedora 30.

**Comment by alexeilebedev** [comment]
That's no longer an initial build failure :-)

In any case, gcc9 is now supported, but you'll need to set COMPILER=g++-9

**Comment by j-joshua** [comment]
Initial build is good.
