### ISSUE TITLE
MacOS Catalina (10.15) breaks OpenAcr

### ISSUE THREAD

**Issue by Quinn1415** [alexeilebedev/openacr#12]
OpenAcr is no longer built with the latest MacOS release 10.15.

% ai

+ mkdir -p temp
+ mkdir -p build/Darwin-clang++.release-x86_64
+ clang++ -O -Werror -ffunction-sections -Wsequence-point -Wno-multichar -Wshadow -pipe -Wextra -Winit-self -Wmissing-include-dirs -Wmissing-declarations -Wno-enum-compare -Wno-array-bounds -Wno-error -iquote . -msse4.2 -D AOS_SSE42 -Wno-vla -fpch-preprocess -c include/algo_pch.hpp -o build/Darwin-clang++.release-x86_64/include.algo_pch.hpp.gch
In file included from include/algo_pch.hpp:26:
In file included from ./include/algo.h:37:
./include/algo/lib.h:239:16: warning: 'strptr_Hash' is missing exception specification '__attribute__((nothrow))' [-Wmissing-exception-spec]
    inline u32 strptr_Hash(u32 prev, algo::strptr val);
               ^

**Comment by alexeilebedev** [comment]
I had success on 10.15.2.
Note your error is in a system header.

**Comment by Quinn1415** [comment]
Thanks Alexei. 
It's a pain that Apple keep changing their stuffs.
