### ISSUE TITLE
clang requires a different option for compilation

### ISSUE THREAD

**Issue by vparizhs** [alexeilebedev/openacr#15]
error: unknown warning option '-Wno-implicit-int-float-conversion'; did you mean '-Wno-implicit-float-conversion'? [-Werror,-Wunknown-warning-option]

$ clang -v
clang version 9.0.1 (Red Hat 9.0.1-2.module+el8.2.0+5494+7b8075cf)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/8
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64

Replacing the option with clang suggestion fixes the compilation

**Comment by alexeilebedev** [comment]
Post a pull request with suggested change to tool_opt table
