### ISSUE TITLE
gcc (Ubuntu 4.8.5-4ubuntu8) 4.8.5 build issue 

### ISSUE THREAD

**Issue by aaslyan** [alexeilebedev/openacr#2]
gcc (Ubuntu 4.8.5-4ubuntu8) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE

cpp/lib/algo/backtrace.cpp: In function ‘void Signal(int, siginfo_t*, void*)’:
cpp/lib/algo/backtrace.cpp:239:70: error: invalid use of incomplete type ‘struct Signal(int, siginfo_t*, void*)::ucontext’
     uintptr_t ip = context ? (uintptr_t)(((struct ucontext *)context)->uc_mcontext.gregs[REG_RIP]) : 0;
                                                                      ^
cpp/lib/algo/backtrace.cpp:239:51: error: forward declaration of ‘struct Signal(int, siginfo_t*, void*)::ucontext’
     uintptr_t ip = context ? (uintptr_t)(((struct ucontext *)context)->uc_mcontext.gregs[REG_RIP]) : 0;
                                                   ^

**Comment by alexeilebedev** [comment]
Can you try this patch?

diff --git a/cpp/lib/algo/backtrace.cpp b/cpp/lib/algo/backtrace.cpp
index b48109a..0a80f7d 100644
--- a/cpp/lib/algo/backtrace.cpp
+++ b/cpp/lib/algo/backtrace.cpp
@@ -61,6 +61,7 @@
 #include <dlfcn.h>
 #include <elf.h>
 #include <execinfo.h>// backtrace
+#include <ucontext.h>
 #include <cxxabi.h>// abi::__cxa_demangle
 
 // we need to silently break out on any error to do not cause segfault or exception
@@ -236,7 +237,7 @@ void algo::FatalErrorExit(const char *a) NORETURN {
 
 static void Signal(int signal, siginfo_t *_si, void *context) {
     (void)_si;
-    uintptr_t ip = context ? (uintptr_t)(((struct ucontext *)context)->uc_mcontext.gregs[REG_RIP]) : 0;
+    uintptr_t ip = context ? (uintptr_t)(((ucontext_t *)context)->uc_mcontext.gregs[REG_RIP]) : 0;
     cstring &out=algo_lib::_db.fatalerr;
     out << "algo_lib.signal  location:";
     u64_PrintHex(ip, out, 8, true);

**Comment by alexeilebedev** [comment]
Fixed.
