### ISSUE TITLE
bin/targ-diff script is broken

### ISSUE THREAD

**Issue by vparizhs** [alexeilebedev/openacr#29]
1. git-current-branch became git-current-ref
2. snippet below has a typo: OTHERCOMIT and OTHERCOMMIT

BRANCH=$(git-current-branch)
OTHERCOMIT=$2
if [ "$OTHERCOMMIT" == "" ]; then
    OTHERCOMMIT="HEAD~"
fi

**Comment by alexeilebedev** [comment]
Fixed.
