### ISSUE TITLE
make argtuple available in algo_lib::_db

### ISSUE THREAD

**Issue by vparizhs** [alexeilebedev/openacr#48]
Currently argtuple is local and is not available in algo_lib::_db  -make it available
void gcli::MainArgs(int argc, char **argv) {
    Argtuple argtuple;
    Argtuple_ReadArgv(argtuple, argc,argv,gcli_syntax, gcli_help);

**Comment by alexeilebedev** [comment]
We removed Argtuple in favor of parsing argc,argv directly into command line structs.
