### ISSUE TITLE
compile issues with  g++ version :  (Ubuntu 13.2.0-23ubuntu4)

### ISSUE THREAD

**Issue by pgmabv99** [alexeilebedev/openacr#93]
2 problems running ai :

1. error  compiling   for cpp/gen/algo_lib_gen.cpp

cpp/gen/algo_gen.cpp:11825:22: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
11825 |         parent.ch[j] = rhs_elems[i];

**Fix: change compile script  bin/bootstrap/Linux-g++.release-x86_64 by
      adding        -Wno-stringop-overflow** 

2. Error down the line on cpp/lib_sqlite/vtab.cpp

 cpp/lib_sqlite/vtab.cpp:227:1: error: missing initializer for member ‘sqlite3_module::xIntegrity’ [-Werror=missing-field-initializers]
  227 | };

**Fix: change data/dev/tool_opt.ssim by adding 
dev.tool_opt  tool_opt:Linux-g++.%-%/%-CC:-Wno-missing-field-initializers comment:"av"**

Now the binaries get built .

**Comment by pgmabv99** [comment]
full changes https://github.com/pgmabv99/openacr/commits/av/

**Comment by ali5h** [comment]
fixed by #94
